# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_image',
            field=models.ImageField(null=True, upload_to='my-photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_picture',
            field=models.ImageField(null=True, upload_to='profile-pics'),
        ),
    ]
